const CHECKOUT_SESSION_ERROR_CODES = {
  INVALID_CHECKOUT_ID: 'INVALID_CHECKOUT_ID',
  CHECKOUT_SESSION_NOT_FOUND: 'CHECKOUT_SESSION_NOT_FOUND',
  CHECKOUT_SESSION_EXPIRED: 'CHECKOUT_SESSION_EXPIRED',
  CHECKOUT_SESSION_SUPERSEDED: 'CHECKOUT_SESSION_SUPERSEDED',
  COMMERCIAL_BOUNDARY_CHANGED: 'COMMERCIAL_BOUNDARY_CHANGED',
  CHECKOUT_SESSION_NOT_USABLE: 'CHECKOUT_SESSION_NOT_USABLE',
  SUPERSEDED_PAYMENT_INTENT: 'SUPERSEDED_PAYMENT_INTENT',
  CANONICAL_PAYMENT_INTENT_MISMATCH: 'CANONICAL_PAYMENT_INTENT_MISMATCH',
  STALE_CLIENT_SECRET: 'STALE_CLIENT_SECRET',
  CHECKOUT_SESSION_CONCURRENCY_CONFLICT: 'CHECKOUT_SESSION_CONCURRENCY_CONFLICT',
  VOUCHER_PAYMENT_INTENT_ATTACH_FAILED: 'VOUCHER_PAYMENT_INTENT_ATTACH_FAILED',
  COMMERCIAL_STAY_FINGERPRINT_REQUIRED: 'COMMERCIAL_STAY_FINGERPRINT_REQUIRED',
  COMMERCIAL_STAY_FINGERPRINT_MISMATCH: 'COMMERCIAL_STAY_FINGERPRINT_MISMATCH',
  DUPLICATE_STAY_CONFLICT: 'DUPLICATE_STAY_CONFLICT',
  FINALIZE_IN_PROGRESS: 'FINALIZE_IN_PROGRESS',
  FINALIZE_INTENT_PERSIST_DISABLED: 'FINALIZE_INTENT_PERSIST_DISABLED',
  FINALIZE_INTENT_INVALID: 'FINALIZE_INTENT_INVALID',
  FINALIZE_INTENT_MISSING: 'FINALIZE_INTENT_MISSING',
  FINALIZE_INTENT_HASH_MISMATCH: 'FINALIZE_INTENT_HASH_MISMATCH',
  FINALIZE_INTENT_IMMUTABLE: 'FINALIZE_INTENT_IMMUTABLE',
  FINALIZE_INTENT_REQUIRED: 'FINALIZE_INTENT_REQUIRED',
  FINALIZE_INTENT_METADATA_SYNC_FAILED: 'FINALIZE_INTENT_METADATA_SYNC_FAILED',
  FINALIZE_INTENT_SESSION_VERSION_CONFLICT: 'FINALIZE_INTENT_SESSION_VERSION_CONFLICT'
};

class CheckoutSessionError extends Error {
  constructor(code, message, details = null) {
    super(message || code);
    this.name = 'CheckoutSessionError';
    this.code = code;
    this.details = details;
  }
}

function isCheckoutSessionError(err) {
  return err instanceof CheckoutSessionError;
}

module.exports = {
  CHECKOUT_SESSION_ERROR_CODES,
  CheckoutSessionError,
  isCheckoutSessionError
};
