const SCHEDULED_DELIVERY_WORKER_ENV_FLAG = 'GIFT_VOUCHER_DELIVERY_WORKER_ENABLED';
const SCHEDULED_DELIVERY_WORKER_TICK_MS_ENV = 'GIFT_VOUCHER_DELIVERY_WORKER_TICK_MS';
const SCHEDULED_DELIVERY_WORKER_SWEEPER_TICK_MS_ENV = 'GIFT_VOUCHER_DELIVERY_WORKER_SWEEPER_TICK_MS';
const SCHEDULED_DELIVERY_WORKER_BATCH_SIZE_ENV = 'GIFT_VOUCHER_DELIVERY_WORKER_BATCH_SIZE';
const SCHEDULED_DELIVERY_WORKER_VISIBILITY_TIMEOUT_MS_ENV =
  'GIFT_VOUCHER_DELIVERY_WORKER_VISIBILITY_TIMEOUT_MS';
const SCHEDULED_DELIVERY_WORKER_ID_ENV = 'GIFT_VOUCHER_DELIVERY_WORKER_ID';

const DEFAULT_TICK_MS = 60_000;
const DEFAULT_SWEEPER_TICK_MS = 120_000;
const DEFAULT_BATCH_SIZE = 50;
const DEFAULT_VISIBILITY_TIMEOUT_MS = 5 * 60_000;
const MAX_SCHEDULED_DELIVERY_ATTEMPTS = 3;
const SCHEDULED_DELIVERY_RETRY_BACKOFF_MS = 30 * 60_000;

const DELIVERABLE_STATUSES = ['active', 'partially_redeemed'];

module.exports = {
  SCHEDULED_DELIVERY_WORKER_ENV_FLAG,
  SCHEDULED_DELIVERY_WORKER_TICK_MS_ENV,
  SCHEDULED_DELIVERY_WORKER_SWEEPER_TICK_MS_ENV,
  SCHEDULED_DELIVERY_WORKER_BATCH_SIZE_ENV,
  SCHEDULED_DELIVERY_WORKER_VISIBILITY_TIMEOUT_MS_ENV,
  SCHEDULED_DELIVERY_WORKER_ID_ENV,
  DEFAULT_TICK_MS,
  DEFAULT_SWEEPER_TICK_MS,
  DEFAULT_BATCH_SIZE,
  DEFAULT_VISIBILITY_TIMEOUT_MS,
  MAX_SCHEDULED_DELIVERY_ATTEMPTS,
  SCHEDULED_DELIVERY_RETRY_BACKOFF_MS,
  DELIVERABLE_STATUSES
};
